const itPositions = [
      { name: "Software Developer", regex: /(?:Software\s|Developer)/gi },
      { name: "Web Developer", regex: /(?:Web\s+Developer)/gi },
      { name: "Frontend Developer", regex: /(?:Frontend\s+Developer)/gi },
      { name: "Backend Developer", regex: /(?:Backend\s+Developer)/gi },
      { name: "Full Stack Developer", regex: /(?:Full\s+Stack\s+Developer)/gi },
      { name: "DevOps Engineer", regex: /(?:DevOps\s+Engineer)/gi },
      { name: "Database Administrator", regex: /(?:Database\s+Administrator|DBA)/gi },
      { name: "Data Scientist", regex: /(?:Data\s+Scientist)/gi },
      { name: "Data Analyst", regex: /(?:Data\s+Analyst)/gi },
      { name: "UI/UX Designer", regex: /(?:UI\/UX\s+Designer)/gi },
      { name: "Systems Administrator", regex: /(?:Systems\s+Administrator)/gi },
      { name: "Network Engineer", regex: /(?:Network\s+Engineer)/gi },
      { name: "Security Analyst", regex: /(?:Security\s+Analyst)/gi },
      { name: "Business Analyst", regex: /(?:Business\s+Analyst)/gi },
      { name: "QA Engineer", regex: /(?:QA\s+Engineer|Quality\s+Assurance\s+Engineer)/gi },
      { name: "Machine Learning Engineer", regex: /(?:Machine\s+Learning\s+Engineer|ML\s+Engineer)/gi },
      { name: "Artificial Intelligence Engineer", regex: /(?:Artificial\s+Intelligence\s+Engineer|AI\s+Engineer)/gi },
      { name: "Cloud Engineer", regex: /(?:Cloud\s+Engineer)/gi },
      { name: "Mobile App Developer", regex: /(?:Mobile\s+App\s+Developer)/gi },
      { name: "Software Architect", regex: /(?:Software\s+Architect)/gi },
      { name: "Technical Support Engineer", regex: /(?:Technical\s+Support\s+Engineer)/gi },
      { name: "Site Reliability Engineer", regex: /(?:Site\s+Reliability\s+Engineer|SRE)/gi },
      { name: "Big Data Engineer", regex: /(?:Big\s+Data\s+Engineer)/gi },
      { name: "Embedded Systems Engineer", regex: /(?:Embedded\s+Systems\s+Engineer)/gi },
      { name: "IT Manager", regex: /(?:IT\s+Manager)/gi },
      { name: "Network Administrator", regex: /(?:Network\s+Administrator)/gi },
      { name: "Chief Technology Officer", regex: /(?:Chief\s+Technology\s+Officer|CTO)/gi },
      { name: "Chief Information Officer", regex: /(?:Chief\s+Information\s+Officer|CIO)/gi },
      { name: "Scrum Master", regex: /(?:Scrum\s+Master)/gi },
      { name: "Product Manager", regex: /(?:Product\s+Manager)/gi },
      { name: "Technical Writer", regex: /(?:Technical\s+Writer)/gi },
      { name: "Game Developer", regex: /(?:Game\s+Developer)/gi },
      { name: "Unity Developer", regex: /(?:Unity\s+Developer)/gi },
      { name: "Mobile App Designer", regex: /(?:Mobile\s+App\s+Designer)/gi },
      { name: "Cloud Architect", regex: /(?:Cloud\s+Architect)/gi },
      { name: "Blockchain Developer", regex: /(?:Blockchain\s+Developer)/gi },
      { name: "IoT Engineer", regex: /(?:IoT\s+Engineer)/gi },
      { name: "Automation Engineer", regex: /(?:Automation\s+Engineer)/gi },
      { name: "AR/VR Developer", regex: /(?:AR\/VR\s+Developer)/gi },
      { name: "Quality Assurance Analyst", regex: /(?:Quality\s+Assurance\s+Analyst|QA\s+Analyst)/gi },
      { name: "Network Security Engineer", regex: /(?:Network\s+Security\s+Engineer)/gi },
      { name: "Business Intelligence Analyst", regex: /(?:Business\s+Intelligence\s+Analyst|BI\s+Analyst)/gi },
      { name: "User Interface Designer", regex: /(?:User\s+Interface\s+Designer|UI\s+Designer)/gi },
      { name: "User Experience Designer", regex: /(?:User\s+Experience\s+Designer|UX\s+Designer)/gi },
      { name: "Linux System Administrator", regex: /(?:Linux\s+System\s+Administrator)/gi },
      { name: "Windows System Administrator", regex: /(?:Windows\s+System\s+Administrator)/gi },
      { name: "Network Administrator", regex: /(?:Network\s+Administrator)/gi },
      { name: "IT Support Specialist", regex: /(?:IT\s+Support\s+Specialist)/gi },
      { name: "Software Tester", regex: /(?:Software\s+Tester|Software\s+QA)/gi },
      { name: "IT Consultant", regex: /(?:IT\s+Consultant)/gi },
      { name: "Technical Consultant", regex: /(?:Technical\s+Consultant)/gi },
      { name: "Machine Learning Scientist", regex: /(?:Machine\s+Learning\s+Scientist|ML\s+Scientist)/gi },
      { name: "Data Engineer", regex: /(?:Data\s+Engineer)/gi },
      { name: "Data Warehouse Developer", regex: /(?:Data\s+Warehouse\s+Developer)/gi },
      { name: "Cloud Security Engineer", regex: /(?:Cloud\s+Security\s+Engineer)/gi },
      { name: "Network Architect", regex: /(?:Network\s+Architect)/gi },
      { name: "System Analyst", regex: /(?:System\s+Analyst)/gi },
      { name: "Firmware Engineer", regex: /(?:Firmware\s+Engineer)/gi },
      { name: "UX Researcher", regex: /(?:UX\s+Researcher)/gi },
      { name: "IT Trainer", regex: /(?:IT\s+Trainer)/gi },
  ];

module.exports = itPositions